### ISSUE TITLE
Redundant section: Customizations > Confirm Bolus Faster on Apple Watch

### ISSUE THREAD

**Issue by snickerdoodleparent** [nightscout/Open-iAPS-docs#45]
[Customizations > Confirm Bolus Faster on Apple Watch](https://docs.diy-trio.org/en/latest/operate/customize.html#confirm-bolus-faster-on-apple-watch) is this section redundant or still needed? 

Does it make sense to point to Mike's addition of a slider under Watch settings:
Settings ⚙️ > Watch > Confirm Bolus Faster 
_Adds an option to reduce the amount you need to spin the crown on an Apple Watch to confirm a bolus._

If a different watch crown speed is required, ... _existing text._

**Comment by MikePlante1** [comment]
Probably best to just remove this from the docs now. Thanks for pointing it out.

**Comment by snickerdoodleparent** [comment]
[PR 49 ](https://github.com/nightscout/trio-docs/pull/49)
