### ISSUE TITLE
Weighted TDD

### ISSUE THREAD

**Issue by marionbarker** [nightscout/Open-iAPS-docs#63]
**Describe the error**
The weighted TDD is reported as 24 hour and 14 day in several places.
It should be 10 day, not 14 day.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by marionbarker** [comment]
This can be closed when #60 is merged and published.

**Comment by MikePlante1** [comment]
Fixed in #60 , so closing this issue now. Thanks!
