### ISSUE TITLE
✏️ Typo in `Recommended Bolus Percentage `  default value

### ISSUE THREAD

**Issue by ebouchut** [nightscout/Open-iAPS-docs#77]
## Describe the error

In the [**Trio Main Preferences**](https://docs.diy-trio.org/en/latest/settings/configuration/preferences/trio.html#recommended-bolus-percentage), section **Recommended Bolus Percentage**, the default value is `80` whereas it should be `70`.
I don't recall changing this value, so `70` should be the default value.

## Screenshots

![typo-recommended_bolus_percentage-default](https://github.com/user-attachments/assets/00ebd0e3-f949-4052-9494-a0dfbffd6fe3)

![typo-recommended_bolus_percentage-app](https://github.com/user-attachments/assets/6a6fd38e-7e85-4154-85ef-fec6121b2a74)

## Additional context

If this makes a difference, when I configured Trio, the first thing I did was to set 'glucose units' to 'mg/dL' first.

**Comment by Natolida** [comment]
Can confirm the default value was 70% in my recent build.

**Comment by ebouchut** [comment]
PR #78 fixed this issue.
